export { default as VkIcon } from './VkIcon'
export { default as GitHubIcon } from './GitHubIcon'
export { default as TgIcon } from './TgIcon'
export { default as YaMusicIcon } from './YaMusicIcon'
export { default as MenuIcon } from './MenuIcon'
